apiVersion: v1
kind: Service
metadata:
  name: blocksout-frontend
  labels:
    app: blocksout-frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: blocksout-frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blocksout-frontend
  labels:
    app: blocksout-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blocksout-frontend
  template:
    metadata:
      labels:
        app: blocksout-frontend
    spec:
      containers:
        - name: blockscout-stack-frontend
          image: "ghcr.io/blockscout/frontend:latest"
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 1Gi
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: NEXT_PUBLIC_NETWORK_ID
              value: "1"
            - name: NEXT_PUBLIC_NETWORK_NAME
              value: "Ether"
            - name: NEXT_PUBLIC_NETWORK_SHORT_NAME
              value: "Ether"
            - name: NEXT_PUBLIC_NETWORK_CURRENCY_NAME
              value: "Ether"
            - name: NEXT_PUBLIC_NETWORK_CURRENCY_SYMBOL
              value: "ETH"
            - name: NEXT_PUBLIC_NETWORK_CURRENCY_DECIMALS
              value: "18"
            - name: NEXT_PUBLIC_API_SPEC_URL
              value: "https://raw.githubusercontent.com/blockscout/blockscout-api-v2-swagger/main/swagger.yaml"

          readinessProbe:
            httpGet:
              path: /api/healthz
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 30
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: http
              scheme: HTTP
            initialDelaySeconds: 100
            periodSeconds: 100
            timeoutSeconds: 30
