apiVersion: v1
kind: Service
metadata:
  name: blockscout
  labels:
    app: blocksout
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: blocksout
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blocksout
  labels:
    app: blocksout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blocksout
  template:
    metadata:
      labels:
        app: blocksout
    spec:
      initContainers:
        - name: init-migrations
          image: "blockscout/blockscout:latest"
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          command:
            - /bin/sh
          args:
            - -c
            - bin/blockscout eval "Elixir.Explorer.ReleaseTasks.create_and_migrate()"
          env:
            - name: PORT
              value: "4000"
            - name: CHAIN_ID
              value: "11155111"
            - name: COIN
              value: "ETH"
            - name: COIN_NAME
              value: "ETH"
            - name: API_V2_ENABLED
              value: "true"
            - name: ETHEREUM_JSONRPC_HTTP_URL
              value: "https://ethereum-sepolia.publicnode.com"
            - name: ETHEREUM_JSONRPC_TRACE_URL
              value: "https://ethereum-sepolia.publicnode.com"
            - name: ETHEREUM_JSONRPC_WS_URL
              value: "wss://ethereum-sepolia.publicnode.com"
            - name: ETHEREUM_JSONRPC_VARIANT
              value: "geth"
            - name: DATABASE_URL
              value: "postgresql://blockscout:blockscout@blockscout-postgres:5432/blockscout"
            - name: ETHEREUM_JSONRPC_VARIANT
              value: "geth"
            - name: ETHEREUM_JSONRPC_VARIANT
              value: "geth"
            - name: ETHEREUM_JSONRPC_VARIANT
              value: "geth"
            - name: SECRET_KEY_BASE
              value: "56NtB48ear7+wMSf0IQuWDAAazhpb31qyc7GiyspBP2vh7t5zlCsF5QDv76chXeN"

      containers:
        - name: bblockscout
          image: "blockscout/blockscout:latest"
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 2Gi
          command:
            - /bin/sh
          args:
            - -c
            - bin/blockscout start
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          env:
            - name: PORT
              value: "4000"
            - name: CHAIN_ID
              value: "1"
            - name: COIN
              value: "ETH"
            - name: COIN_NAME
              value: "ETH"
            - name: API_V2_ENABLED
              value: "true"
            - name: ETHEREUM_JSONRPC_HTTP_URL
              value: "https://ethereum-sepolia.publicnode.com"
            - name: ETHEREUM_JSONRPC_TRACE_URL
              value: "https://ethereum-sepolia.publicnode.com"
            - name: ETHEREUM_JSONRPC_WS_URL
              value: "wss://ethereum-sepolia.publicnode.com"
            - name: ETHEREUM_JSONRPC_VARIANT
              value: "geth"
            - name: DATABASE_URL
              value: "postgresql://blockscout:blockscout@blockscout-postgres:5432/blockscout"
            - name: ETHEREUM_JSONRPC_VARIANT
              value: "geth"
            - name: ETHEREUM_JSONRPC_VARIANT
              value: "geth"
            - name: ETHEREUM_JSONRPC_VARIANT
              value: "geth"
            - name: SECRET_KEY_BASE
              value: "56NtB48ear7+wMSf0IQuWDAAazhpb31qyc7GiyspBP2vh7t5zlCsF5QDv76chXeN"

          readinessProbe:
            httpGet:
              path: /api/v1/health/readiness
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 60
          livenessProbe:
            httpGet:
              path: /api/v1/health/liveness
              port: http
              scheme: HTTP
            initialDelaySeconds: 100
            periodSeconds: 100
            timeoutSeconds: 30
