---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stats-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats-postgres
  template:
    metadata:
      labels:
        app: stats-postgres
    spec:
      containers:
        - name: db
          image: postgres:14
          env:
            - name: POSTGRES_DB
              value: "stats"
            - name: POSTGRES_USER
              value: "blockscout"
            - name: POSTGRES_PASSWORD
              value: "blockscout"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - stats
                - -d
                - stats
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - blockscout
                - -d
                - blockscout
            initialDelaySeconds: 10
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: db-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: stats-postgres
spec:
  ports:
    - port: 5432
  selector:
    app: stats-postgres
